openai:
  api-key: YOUR_KEY

whatsapp:
  #token: EAAhm8FfxHKQBQur5jmCdMV3LqHjlM1vSW7VZB7Ai1lTZAW9weXqDgcOIounSM0xOlUXZAKVZArROYBgKDZCSrRZBuyZBNdOiiw0PtUytqGZCMi5iNtarPDZCJEMNz3P2IoubumIqvAy0wWcZANl8nvnqFEN81XcthIOZAozPCnBV6O4HuCnOc53ZATLU6whJ7D8lur23iOuywqtkIy5GunEMMPl2Y4ZAdb6z6ly2FAFYNfe4yZC7Yh4cZAxBmZCdi5GVYhsdXQwMo6QHWFLmQc9tNnokCb8O
  phone-id: 942189068982240

google:
  drive:
    folder-id: AI_TASK_FOLDER_ID